services:
  redis:
    image: redis:7.0.15
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    environment:
      TOKEN: ${TELEGRAM_BOT_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    volumes:  
      - ./app/chats:/app/app/chats
      - ./app/temp:/app/app/temp

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    restart: always
    volumes:
      - ./database.db:/app/database.db

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    restart: always
    expose:
      - "5000"

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    ports:
      - "8087:8087"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
