# Use an official Python runtime as a parent image
FROM python:3.12.3-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt ./

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code into the container
COPY . .

# Ensure the .env file is included
COPY .env .env

# Set environment variables (optional, adjust as needed)
ENV PYTHONUNBUFFERED=1

# Run the bot
CMD ["python", "main.py"]